services:
  social-graph-neo4j:
    image: neo4j:5.23
    ports:
      - "7474:7474"
      - "7687:7687"
      
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
      
  rabbitMq:
    image: rabbitmq:management-alpine
    ports:
      - "15672:15672"
      - "5672:5672"