receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
        
  prometheus/own_metrics:
    config:
      scrape_configs:
        - job_name: otel-collector
          scrape_interval: 10s
          static_configs:
            - targets: [ "0.0.0.0:8888" ]

exporters:
  prometheus:
    endpoint: "0.0.0.0:9090"
  debug:
  otlp:
    endpoint: "jaeger:4317"
    tls:
      insecure: true
processors:
  batch:
    
extensions:
  zpages:

service:
  extensions: [zpages]
  pipelines:
    metrics:
      receivers: [otlp,prometheus/own_metrics]
      processors: [batch]
      exporters: [prometheus, debug]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp, debug]