services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
      ME_CONFIG_BASICAUTH: false
  
  media-service:
    image: mqsr/zylo/media-service:1.0.0
    ports:
      - "8082:8080"
    env_file:
      - .env