// Code generated by mockery v2.46.0. DO NOT EDIT.

package proto

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockUserProfileServiceServer is an autogenerated mock type for the UserProfileServiceServer type
type MockUserProfileServiceServer struct {
	mock.Mock
}

type MockUserProfileServiceServer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserProfileServiceServer) EXPECT() *MockUserProfileServiceServer_Expecter {
	return &MockUserProfileServiceServer_Expecter{mock: &_m.Mock}
}

// GetProfilePicture provides a mock function with given fields: _a0, _a1
func (_m *MockUserProfileServiceServer) GetProfilePicture(_a0 context.Context, _a1 *UserProfileRequest) (*UserProfileResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetProfilePicture")
	}

	var r0 *UserProfileResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *UserProfileRequest) (*UserProfileResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *UserProfileRequest) *UserProfileResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*UserProfileResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *UserProfileRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserProfileServiceServer_GetProfilePicture_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProfilePicture'
type MockUserProfileServiceServer_GetProfilePicture_Call struct {
	*mock.Call
}

// GetProfilePicture is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *UserProfileRequest
func (_e *MockUserProfileServiceServer_Expecter) GetProfilePicture(_a0 interface{}, _a1 interface{}) *MockUserProfileServiceServer_GetProfilePicture_Call {
	return &MockUserProfileServiceServer_GetProfilePicture_Call{Call: _e.mock.On("GetProfilePicture", _a0, _a1)}
}

func (_c *MockUserProfileServiceServer_GetProfilePicture_Call) Run(run func(_a0 context.Context, _a1 *UserProfileRequest)) *MockUserProfileServiceServer_GetProfilePicture_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*UserProfileRequest))
	})
	return _c
}

func (_c *MockUserProfileServiceServer_GetProfilePicture_Call) Return(_a0 *UserProfileResponse, _a1 error) *MockUserProfileServiceServer_GetProfilePicture_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserProfileServiceServer_GetProfilePicture_Call) RunAndReturn(run func(context.Context, *UserProfileRequest) (*UserProfileResponse, error)) *MockUserProfileServiceServer_GetProfilePicture_Call {
	_c.Call.Return(run)
	return _c
}

// mustEmbedUnimplementedUserProfileServiceServer provides a mock function with given fields:
func (_m *MockUserProfileServiceServer) mustEmbedUnimplementedUserProfileServiceServer() {
	_m.Called()
}

// MockUserProfileServiceServer_mustEmbedUnimplementedUserProfileServiceServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'mustEmbedUnimplementedUserProfileServiceServer'
type MockUserProfileServiceServer_mustEmbedUnimplementedUserProfileServiceServer_Call struct {
	*mock.Call
}

// mustEmbedUnimplementedUserProfileServiceServer is a helper method to define mock.On call
func (_e *MockUserProfileServiceServer_Expecter) mustEmbedUnimplementedUserProfileServiceServer() *MockUserProfileServiceServer_mustEmbedUnimplementedUserProfileServiceServer_Call {
	return &MockUserProfileServiceServer_mustEmbedUnimplementedUserProfileServiceServer_Call{Call: _e.mock.On("mustEmbedUnimplementedUserProfileServiceServer")}
}

func (_c *MockUserProfileServiceServer_mustEmbedUnimplementedUserProfileServiceServer_Call) Run(run func()) *MockUserProfileServiceServer_mustEmbedUnimplementedUserProfileServiceServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUserProfileServiceServer_mustEmbedUnimplementedUserProfileServiceServer_Call) Return() *MockUserProfileServiceServer_mustEmbedUnimplementedUserProfileServiceServer_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockUserProfileServiceServer_mustEmbedUnimplementedUserProfileServiceServer_Call) RunAndReturn(run func()) *MockUserProfileServiceServer_mustEmbedUnimplementedUserProfileServiceServer_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserProfileServiceServer creates a new instance of MockUserProfileServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserProfileServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserProfileServiceServer {
	mock := &MockUserProfileServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
