// Code generated by mockery v2.46.0. DO NOT EDIT.

package proto

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"
)

// MockUserProfileServiceClient is an autogenerated mock type for the UserProfileServiceClient type
type MockUserProfileServiceClient struct {
	mock.Mock
}

type MockUserProfileServiceClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserProfileServiceClient) EXPECT() *MockUserProfileServiceClient_Expecter {
	return &MockUserProfileServiceClient_Expecter{mock: &_m.Mock}
}

// GetProfilePicture provides a mock function with given fields: ctx, in, opts
func (_m *MockUserProfileServiceClient) GetProfilePicture(ctx context.Context, in *UserProfileRequest, opts ...grpc.CallOption) (*UserProfileResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetProfilePicture")
	}

	var r0 *UserProfileResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *UserProfileRequest, ...grpc.CallOption) (*UserProfileResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *UserProfileRequest, ...grpc.CallOption) *UserProfileResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*UserProfileResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *UserProfileRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserProfileServiceClient_GetProfilePicture_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProfilePicture'
type MockUserProfileServiceClient_GetProfilePicture_Call struct {
	*mock.Call
}

// GetProfilePicture is a helper method to define mock.On call
//   - ctx context.Context
//   - in *UserProfileRequest
//   - opts ...grpc.CallOption
func (_e *MockUserProfileServiceClient_Expecter) GetProfilePicture(ctx interface{}, in interface{}, opts ...interface{}) *MockUserProfileServiceClient_GetProfilePicture_Call {
	return &MockUserProfileServiceClient_GetProfilePicture_Call{Call: _e.mock.On("GetProfilePicture",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockUserProfileServiceClient_GetProfilePicture_Call) Run(run func(ctx context.Context, in *UserProfileRequest, opts ...grpc.CallOption)) *MockUserProfileServiceClient_GetProfilePicture_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*UserProfileRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockUserProfileServiceClient_GetProfilePicture_Call) Return(_a0 *UserProfileResponse, _a1 error) *MockUserProfileServiceClient_GetProfilePicture_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserProfileServiceClient_GetProfilePicture_Call) RunAndReturn(run func(context.Context, *UserProfileRequest, ...grpc.CallOption) (*UserProfileResponse, error)) *MockUserProfileServiceClient_GetProfilePicture_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserProfileServiceClient creates a new instance of MockUserProfileServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserProfileServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserProfileServiceClient {
	mock := &MockUserProfileServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
