// Code generated by mockery v2.46.0. DO NOT EDIT.

package proto

import mock "github.com/stretchr/testify/mock"

// MockUnsafeUserProfileServiceServer is an autogenerated mock type for the UnsafeUserProfileServiceServer type
type MockUnsafeUserProfileServiceServer struct {
	mock.Mock
}

type MockUnsafeUserProfileServiceServer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUnsafeUserProfileServiceServer) EXPECT() *MockUnsafeUserProfileServiceServer_Expecter {
	return &MockUnsafeUserProfileServiceServer_Expecter{mock: &_m.Mock}
}

// mustEmbedUnimplementedUserProfileServiceServer provides a mock function with given fields:
func (_m *MockUnsafeUserProfileServiceServer) mustEmbedUnimplementedUserProfileServiceServer() {
	_m.Called()
}

// MockUnsafeUserProfileServiceServer_mustEmbedUnimplementedUserProfileServiceServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'mustEmbedUnimplementedUserProfileServiceServer'
type MockUnsafeUserProfileServiceServer_mustEmbedUnimplementedUserProfileServiceServer_Call struct {
	*mock.Call
}

// mustEmbedUnimplementedUserProfileServiceServer is a helper method to define mock.On call
func (_e *MockUnsafeUserProfileServiceServer_Expecter) mustEmbedUnimplementedUserProfileServiceServer() *MockUnsafeUserProfileServiceServer_mustEmbedUnimplementedUserProfileServiceServer_Call {
	return &MockUnsafeUserProfileServiceServer_mustEmbedUnimplementedUserProfileServiceServer_Call{Call: _e.mock.On("mustEmbedUnimplementedUserProfileServiceServer")}
}

func (_c *MockUnsafeUserProfileServiceServer_mustEmbedUnimplementedUserProfileServiceServer_Call) Run(run func()) *MockUnsafeUserProfileServiceServer_mustEmbedUnimplementedUserProfileServiceServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUnsafeUserProfileServiceServer_mustEmbedUnimplementedUserProfileServiceServer_Call) Return() *MockUnsafeUserProfileServiceServer_mustEmbedUnimplementedUserProfileServiceServer_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockUnsafeUserProfileServiceServer_mustEmbedUnimplementedUserProfileServiceServer_Call) RunAndReturn(run func()) *MockUnsafeUserProfileServiceServer_mustEmbedUnimplementedUserProfileServiceServer_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUnsafeUserProfileServiceServer creates a new instance of MockUnsafeUserProfileServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUnsafeUserProfileServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUnsafeUserProfileServiceServer {
	mock := &MockUnsafeUserProfileServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
