global:
  env:
    ASPNETCORE_ENVIRONMENT: ""
    AZURE_CLIENT_ID: ""
    AZURE_CLIENT_SECRET: ""
    AZURE_TENANT_ID: ""
    AZURE_VAULT_NAME: ""
    AWS_ACCESS_KEY_ID: ""
    AWS_SECRET_ACCESS_KEY: ""
    AWS_REGION: ""

replicaCount: 1

image:
  repository: mqsr/zylo/user-interaction
  pullPolicy: Always
  tag: "1.0.0"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}

  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}


service:
  type: ClusterIP
  targetPort: 8080
  port: 8080



env:
  ASPNETCORE_ENVIRONMENT:
    name: "azure-key-vault"
    key: "ASPNETCORE_ENVIRONMENT"

  AWS_ACCESS_KEY_ID:
    name: "aws-secrets"
    key: "accessKey"

  AWS_SECRET_ACCESS_KEY:
    name: "aws-secrets"
    key: "secretKey"

  AWS_REGION:
    name: "aws-secrets"
    key: "region"

  AZURE_CLIENT_ID:
    name: "azure-key-vault"
    key: "clientId"

  AZURE_CLIENT_SECRET:
    name: "azure-key-vault"
    key: "clientSecret"

  AZURE_TENANT_ID:
    name: "azure-key-vault"
    key: "tenantId"

  AZURE_VAULT_NAME:
    name: "azure-key-vault"
    key: "vaultName"


resources: {}

readinessProbe:
  httpGet:
    path: /
    port: http

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []

volumeMounts: []