name: Build Feed Service

on:
  push:
    paths:
      - 'feed-service/**'
      - '.github/feed-service.yml'
  pull_request:
    paths:
      - 'feed-service/**'
      - '.github/feed-service.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/feed-service
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Install dependencies
        run: go mod tidy

      - name: Build the project
        run: go build -o build/feed-service ./...
