name: Build Feed Service

on:
  push:
    branches:
      - main
    paths:
      - 'src/feed-service/**'
      - '.github/workflows/feed-service.yml'
    tags:
      - 'feed-service/v*.*.*'
  pull_request:
    branches:
      - main
    paths:
      - 'src/feed-service/**'
      - '.github/workflows/feed-service.yml'

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/feed-service
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Install dependencies
        run: go mod tidy

      - name: Build the project
        run: go build ./cmd/feed-service

  security-scan:
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/feed-service
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload scan results to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'

  docker-build-and-push:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ secrets.FEED_SERVICE_DOCKER_IMAGE }}
          tags: |
            type=match,pattern=feed-service/v(.*),group=1
            type=match,pattern=feed-service/v(\d.\d),group=1
            type=match,pattern=feed-service/v(\d),group=1
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          file: src/feed-service/Dockerfile
          context: src/feed-service
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: '${{ fromJSON(steps.meta.outputs.json).tags[1] }}'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload scan results to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'
