name: "Build Notification Service"

on:
  push:
    branches:
      - main
    paths:
      - 'src/notification-service/**'
      - '.github/workflows/notification-service.yml'
    tags:
      - 'notification-service/v*.*.*'
  pull_request:
    branches:
      - main
    paths:
      - 'src/notification-service/**'
      - '.github/workflows/notification-service.yml'

permissions:
  contents: read
  security-events: write
  actions: read
  
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/notification-service
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'


      - name: Restore dependencies
        run: dotnet restore NotificationService/NotificationService.csproj

      - name: Build
        run: dotnet build NotificationService/NotificationService.csproj --no-restore --configuration Release
